name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: "testing"
  cancel-in-progress: true

jobs:

  ios-tests:
    name: iOS Tests
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4

      - name: Switch Xcode 🔄
        run: sudo xcode-select --switch /Applications/Xcode_15.0.app

      - name: Test iOS
        run: >
          xcodebuild test
          -scheme fs-itunes-search-client
          -destination "platform=iOS Simulator,name=iPhone 15"
          -enableCodeCoverage YES
          -skipPackagePluginValidation

      - name: Fetch Coverage
        uses: sersoft-gmbh/swift-coverage-action@v4
        id: coverage-files

      - name: Publish Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ${{ join(fromJSON(steps.coverage-files.outputs.files), ',') }}


  macos-tests:
    name: macOS Tests
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4

      - name: Switch Xcode 🔄
        run: sudo xcode-select --switch /Applications/Xcode_15.0.app

      - name: Test macOS
        run: >
          xcodebuild test
          -scheme fs-itunes-search-client
          -destination "platform=macOS"
          -enableCodeCoverage YES
          -skipPackagePluginValidation
